name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
      - name: build code
        run: npm run build
